/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class samples_App */

#ifndef _Included_samples_App
#define _Included_samples_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     samples_App
 * Method:    printCalcul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_samples_App_printCalcul
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     samples_App
 * Method:    printName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_samples_App_printName
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
